version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: event-postgres
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5432:5432"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8080"

  event-service:
    build: ./event-service
    container_name: event-service
    depends_on:
      - postgres
      - eureka-server
    ports:
      - "8081:8080"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    depends_on:
      - event-service
      - eureka-server
    ports:
      - "8082:8080"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - eureka-server
    ports:
      - "8083:8080"
